// This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.

import inquirer from "inquirer";

// Generate a random number between 1 and 10
const randomNumber = Math.floor(Math.random() * 10) + 1;

// Function to start the game
async function startGame() {
  const answer = await inquirer.prompt([
    {
      type: "number",
      name: "userGuess",
      message: "Guess a number between 1 and 10:",
    },
  ]);

  const userGuess = answer.userGuess;

  if (userGuess === randomNumber) {
    console.log("Congratulations! You guessed the correct number!");
  } else {
    console.log(`Sorry, the correct number was ${randomNumber}. Try again!`);
  }}

//Calling A function
startGame();
